### PR TITLE
add README

### PR DESCRIPTION
**Pull request by naskio**
# Description
- Adding initial version of organization profile README

# TODO
1. [x] Update repo description to
```
Organization profile README
```

### CODE REVIEW

**Review by stackedsax — COMMENTED** [review]
@c-rindi do we want to highlight Siembol here?  

Also, I kinda would prefer the subtitle to be "CREATE TODAY.  PREDICT TOMORROW." rather than the somewhat uninspiring "We are a leading quantitative research and technology firm."  We say that in the paragraph below, anyway.

**Comment by naskio** [comment]
@stackedsax My bad, we already agreed that it should be replaced by ILGPU.
I made few more changes:
- Using older GR-OSS logo as requested.
- Using the suggested slogan.
- Replacing Siembol with ILGPU.
- Adding CTA to Community section.
- Adding badges.

**Review by stackedsax — APPROVED** [review]
Looks great!

The only addition I'd make is: 

`[Armada](https://github.com/armadaproject/armada): A multi-cluster batch queuing system for high-throughput workloads on Kubernetes, designed primarily for data science and machine learning.  Armada is part of the CNCF Sandbox.`

If you want to do that in another PR later, totally fine.

**Comment by naskio** [comment]
Yes 👌
Seems better

**Pull request merged**
